services:
  backend:
    build:
      context: ./backend100theme
      dockerfile: DockerFile
    ports:
      - "3050:3050" # แมปพอร์ต 3001 บนเครื่อง host กับ 3000 ใน container ของ backend
    restart: always
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

  frontend:
    build:
      context: ./manageThemeColor
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # แมปพอร์ต 3000 บนเครื่อง host กับ 3000 ใน container ของ frontend
    depends_on:
      - backend
    restart: always
