import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/component/layout_component/Navbar";
import Sidebar from "@/src/component/layout_component/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex flex-col min-h-screen bg-zinc-50 font-sans dark:bg-black">
        <Navbar />
        <div className="flex flex-1 overflow-hidden">
          <Sidebar />
          <main className="flex-1 w-full bg-zinc-100/50 dark:bg-zinc-950/50 overflow-y-auto h-[calc(100vh-4rem)] p-6 md:p-10">
            <div className="max-w-6xl mx-auto flex flex-col gap-8">
              {children}
              <div className="flex justify-center mt-4 pb-4">
                <p>Theme web | @2026</p>
              </div>
            </div>
          </main>
          {/* Footer Skeleton */}
        </div>
      </body>
    </html>
  );
}
