name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Frontend Dependencies and Lint
        run: |
          cd manageThemeColor
          npm install
          npm run lint

      - name: Build Docker Images
        run: docker compose up -d --build
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Deployment Success
        run: echo "Deployment Success!"

  notify:
    needs: [build]
    runs-on: ubuntu-latest
    # if: always()
    steps:
      # - name: Discord Notification
      #   uses: sarisia/actions-status-discord@v1
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #     status: ${{ needs.build.result }}
      #     title: "🚀 อัปเดตสถานะการทำงาน (CI/CD)"
      #     description: "อัปเดตล่าสุดจาก Repository ของคุณ ตรวจสอบรายละเอียดได้เลยครับ!"
      #     username: "Spoky Doggo"

      - name: Success Alert
        if: ${{ needs.build.result == 'success' }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: "🚀 อัปเดตสถานะการทำงาน (CI/CD)"
          description: "อัปเดตล่าสุดจาก Repository ของคุณ ตรวจสอบรายละเอียดได้เลยครับ!"
          username: "Spoky Doggo"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "🎉 **Success!** เก่งมาก ยินดีด้วยนะ น้องรัก"

      - name: Failure Alert
        if: ${{ needs.build.result == 'failure' }}
        uses: sarisia/actions-status-discord@v1
        with:
          title: "🚀 อัปเดตสถานะการทำงาน (CI/CD)"
          description: "อัปเดตล่าสุดจาก Repository ของคุณ ตรวจสอบรายละเอียดได้เลยครับ!"
          username: "Spoky Doggo"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "⚠️ **Failure** ไม่เป็นไรนะ น้องรัก กอดๆ ลองใหม่อีกครั้งนะคนเก่งของพี่"
          